# Generated by Django 4.1.4 on 2022-12-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrers',
            name='contact_no',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='carrers',
            name='job_id',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
